version: '3.8'

services: 
  postgres: 
    container_name: nest-system-integration-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432 
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=system-integration