services: 
  postgres: 
    container_name: system-integration-pg
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=system-integration

  redis:
    image: redis:latest
    container_name: system-integration-redis
    command: redis-server --appendonly yes --requirepass university
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: university
    mem_limit: 256mb 