version: '3.8'

services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    container_name: system-integration-rabbitmq
    environment:
      - RABBITMQ_USERNAME=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - RABBITMQ_VHOST=/
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/bitnami/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
