version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://usuario:senha@db:5432/lancamentos_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    restart: on-failure

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=lancamentos_db
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d lancamentos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: